### ISSUE TITLE
Widescreen resolution in OC?

### ISSUE THREAD

**Issue by yceballost** [perez987/macOS-14-Sonoma-on-z390-with-OpenCore#2]
Hi @perez987, thanks for all of this information and resources 🙌

I have a 34" widescreen monitor with 3440x1440 resolution. Do you know if is it possible to have this resolution in OpenCore boot? right now it is displaying an unsupported resolution and looks quit deformed.

I'm using Display Port.

Thanks in advance!

**Comment by perez987** [comment]
@yceballost 
Buenas tardes. Esribo en español y me dices si prefieres que lo cambie a inglés.

Hay usuarios que a veces tienen problemas para ajustar la resolución del menú de OpenCore. Esto se controla principalmente con 2 propiedades que están en `UEFI >> Output`:

- `Resolution`: ajusta la resolución de pantalla en consola.
  - Ajusta a WxH@Bpp (e.g. 1920x1080@32) or WxH (e.g. 1920x1080) para conseguir resoluciones personalizadas.
  - Ajusta a Max para intentar la mayor resolución de pantalla disponible para los datos EDID de la pantalla conectada.
- `UIScale`: factor de escala de la consola. Equivale a la variable 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:UIScale (usa una de las 2, no ambas).
  - 1 — 1x para monitores normaless.
  - 2 — 2x para monitores HiDPI.
  - -1 — mantiene el ajuste actual.
  - 0 — elige el factor de escala automáticamente basado en la resolución actual.

Juega con estas 2 propiedades para ver si consigues lo que deseas. 

También puedes probar cable HDMI en lugar de DP porque a veces el menú de OpenCore se ve con uno de ellos diferente que con el otro aunque no es lo habitual.

¿Qué tarjeta gráfica tienes? Prueba y me vas contando a ver si lo arreglamos.

**Comment by yceballost** [comment]
En español sin problema!

La tarjeta que tengo es AMD Radeon RX 5700 XT 8 GB

Probé a usar UIScale = 2 y con HDMI y se ha resuelto!

Mil gracias!

**Comment by perez987** [comment]
@yceballost 
Ojalá se arreglaran siempre las cosas tan fácilmente!
Un saludo.
